# Generated by Django 5.2.6 on 2026-07-08 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_injectoraccessory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InjectorServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('received_at', models.DateTimeField()),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('resistance', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('leakage', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('notes_before', models.TextField(blank=True)),
                ('notes_after', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Recibido'), ('IN_PROGRESS', 'En proceso'), ('READY', 'Listo'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Anulado')], default='RECEIVED', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('injector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_records', to='customers.injector')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servicio de inyector',
                'verbose_name_plural': 'Servicios de inyectores',
                'db_table': 'customers_injector_service_records',
                'ordering': ['-received_at', '-id'],
            },
        ),
    ]
