# Generated by Django 5.2.6 on 2026-07-08 04:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_injectorservicerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InjectorServiceAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_records', to='customers.injectoraccessory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('service_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='customers.injectorservicerecord')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accesorio utilizado',
                'verbose_name_plural': 'Accesorios utilizados',
                'db_table': 'customers_injector_service_accessories',
                'constraints': [models.UniqueConstraint(fields=('service_record', 'accessory'), name='uq_service_accessory')],
            },
        ),
    ]
