# Generated by Django 5.2.6 on 2026-07-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_injectorserviceaccessory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['display_name'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('PERSON', 'Persona'), ('COMPANY', 'Empresa')], default='PERSON', max_length=20),
        ),
    ]
