# Generated by Django 5.2.6 on 2026-07-08 00:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('shelf_letter', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator(message='La letra del estante debe ser una única letra mayúscula.', regex='^[A-Z]$')])),
                ('shelf_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('code', models.CharField(editable=False, max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Storage Location',
                'verbose_name_plural': 'Storage Locations',
                'db_table': 'inventory_storage_locations',
                'ordering': ['shelf_letter', 'shelf_number'],
                'constraints': [models.UniqueConstraint(fields=('shelf_letter', 'shelf_number'), name='uq_storage_location')],
            },
        ),
    ]
