# Generated by Django 5.2.6 on 2026-07-08 00:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storagelocation',
            options={'ordering': ['shelf_letter', 'shelf_number'], 'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.AddIndex(
            model_name='storagelocation',
            index=models.Index(fields=['shelf_letter'], name='idx_location_shelf'),
        ),
    ]
