# Generated by Django 5.2.6 on 2026-07-08 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supplier_reference', models.CharField(blank=True, help_text='Código usado por el proveedor.', max_length=80)),
                ('manufacturer', models.CharField(blank=True, help_text='Marca o fabricante con el que el proveedor comercializa la pieza.', max_length=100)),
                ('preferred_supplier', models.BooleanField(default=False, help_text='Indica si es el proveedor preferido para este producto.')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_products', to='inventory.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_products', to='inventory.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto de proveedor',
                'verbose_name_plural': 'Productos de proveedores',
                'db_table': 'inventory_supplier_products',
                'ordering': ['supplier__name', 'product__standard_code'],
                'constraints': [models.UniqueConstraint(fields=('supplier', 'product', 'supplier_reference'), name='uq_supplier_product')],
            },
        ),
    ]
