# Generated by Django 5.2.6 on 2026-07-08 01:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_importcostcategory_importcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='importcost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='currency',
            field=models.CharField(choices=[('CRC', 'Colones'), ('USD', 'Dólares')], help_text='ISO 4217.', max_length=3),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
    ]
