# Generated by Django 5.2.6 on 2026-07-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_importcost_is_active_alter_purchase_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='direction',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], default='IN', max_length=3),
        ),
    ]
