# Generated by Django 5.2.6 on 2026-07-08 13:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_inventorycount_inventorycountitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_unit_cost', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('cost_factor', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('final_unit_cost', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('currency', models.CharField(choices=[('CRC', 'Colones'), ('USD', 'Dólares')], max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('margin_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('suggested_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_history', to='inventory.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_cost_history', to='inventory.purchase')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de costo',
                'verbose_name_plural': 'Históricos de costos',
                'db_table': 'inventory_product_cost_history',
                'ordering': ['-calculated_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('product', 'purchase'), name='uq_product_purchase_cost_history')],
            },
        ),
    ]
