# Generated by Django 5.2.6 on 2026-07-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_stockmovement_sale_item'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productcosthistory',
            name='uq_product_purchase_cost_history',
        ),
    ]
