# Generated by Django 5.2.6 on 2026-07-14 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_purchase_cancelled_at_purchase_cancelled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reverses_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_movement', to='inventory.stockmovement'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('ENTRY', 'Entrada'), ('EXIT', 'Salida'), ('ADJUSTMENT', 'Ajuste'), ('INITIAL', 'Inventario inicial'), ('REVERSAL', 'Reversión')], max_length=20),
        ),
    ]
