# Generated by Django 5.2.6 on 2026-08-08 01:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_purchase_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importcost',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Tipo de cambio para convertir este costo a la moneda de la compra.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]),
        ),
    ]
