# Generated by Django 5.2.6 on 2026-08-14 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_importcost_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='inventory_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.inventorycount'),
        ),
    ]
