# Generated by Django 5.2.6 on 2026-09-09 23:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_expected_total_by_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashclosing',
            name='expected_card',
            field=models.DecimalField(decimal_places=4, help_text='Desglose de expected_total: solo lo pagado con tarjeta.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='cashclosing',
            name='expected_cash',
            field=models.DecimalField(decimal_places=4, help_text='Desglose de expected_total: solo lo pagado en efectivo.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='cashclosing',
            name='expected_other',
            field=models.DecimalField(decimal_places=4, help_text='Desglose de expected_total: otros métodos de pago.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='cashclosing',
            name='expected_transfer',
            field=models.DecimalField(decimal_places=4, help_text='Desglose de expected_total: solo lo pagado por transferencia.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
