# Generated by Django 5.2.6 on 2026-07-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_cancelled_at_sale_cancelled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
    ]
